import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const docsRoot = join(repoRoot, "docs");
const zhDocsRoot = join(docsRoot, "zh");
const zhManualRoot = join(docsRoot, ".zh", "manual");
const zhLlmsFullPath = join(docsRoot, "public", "zh", "llms-full.txt");
const siteDocsGeneratorPath = join(repoRoot, "scripts", "generate-site-docs.mjs");
const themeIndexPath = join(docsRoot, ".vitepress", "theme", "index.ts");
const localeRedirectPath = join(docsRoot, ".vitepress", "theme", "localeRedirect.ts");
const generatedNotice =
  "<!-- Generated by scripts/generate-site-docs.mjs. Do not edit directly. -->";
const stalePartialNotice = "中文站目前是维护性摘要和生成参考";
const generatedReferenceNotice = "本页由仓库元数据、API reports 或示例目录生成";
const generatedTopLevelPages = new Set(["examples.md", "index.md", "llms.md"]);
const standaloneTopLevelPages = new Set(["AI-SKILL.md"]);
const repoUrl = "https://github.com/jskits/loggerjs";

const failures = [];

function markdownFiles(dir) {
  const files = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...markdownFiles(path));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith(".md")) files.push(path);
  }
  return files;
}

function jsonStringLiteral(value) {
  return JSON.parse(`"${value}"`);
}

function yamlString(value) {
  return JSON.stringify(value);
}

function normalizeGeneratedOutput(contents) {
  return `${contents.trimEnd()}\n`;
}

function sourceFileLink(path) {
  return `${repoUrl}/blob/main/${path}`;
}

function zhCatalogDocs() {
  const source = readFileSync(siteDocsGeneratorPath, "utf8");
  const match = /const zhDocsCatalog = \[([\s\S]*?)\];\n\nconst packageOrder/.exec(source);
  if (!match?.[1]) {
    failures.push("scripts/generate-site-docs.mjs must expose a parseable zhDocsCatalog");
    return [];
  }

  const docs = [
    ...match[1].matchAll(
      /{\s*title:\s*"((?:\\.|[^"])*)",\s*slug:\s*"((?:\\.|[^"])*)",\s*description:\s*"((?:\\.|[^"])*)"/g,
    ),
  ].map((item) => ({
    description: jsonStringLiteral(item[3]),
    slug: jsonStringLiteral(item[2]),
    title: jsonStringLiteral(item[1]),
  }));
  if (docs.length === 0) {
    failures.push("scripts/generate-site-docs.mjs zhDocsCatalog must contain guide slugs");
  }
  return docs;
}

function expectedChineseGuidePage(doc, body) {
  const related = `\n## 相关链接\n\n- [英文原文](/${doc.slug})\n- [中文首页](/zh/)\n`;
  return normalizeGeneratedOutput(`---
title: ${yamlString(doc.title)}
description: ${yamlString(doc.description)}
---
${generatedNotice}

${body}
${related}
`);
}

const manualFiles = markdownFiles(zhManualRoot);
const zhFiles = markdownFiles(zhDocsRoot);
const catalogDocs = zhCatalogDocs();

for (const doc of catalogDocs) {
  const relativePath = `${doc.slug}.md`;
  const manualPath = join(zhManualRoot, relativePath);
  const generatedPath = join(zhDocsRoot, relativePath);
  if (!existsSync(manualPath)) {
    failures.push(
      `zhDocsCatalog entry ${relativePath} is missing manual source at ${relative(repoRoot, manualPath)}`,
    );
  }
  if (!existsSync(generatedPath)) {
    failures.push(
      `zhDocsCatalog entry ${relativePath} is missing generated page at ${relative(repoRoot, generatedPath)}`,
    );
  }
  if (existsSync(manualPath) && existsSync(generatedPath)) {
    const manualBody = readFileSync(manualPath, "utf8").trim();
    const expected = expectedChineseGuidePage(doc, manualBody);
    const actual = readFileSync(generatedPath, "utf8");
    if (actual !== expected) {
      failures.push(
        `${relative(repoRoot, generatedPath)} is stale; run pnpm docs:generate after editing ${relative(repoRoot, manualPath)}`,
      );
    }
  }
}

if (existsSync(zhLlmsFullPath)) {
  const zhLlmsFull = readFileSync(zhLlmsFullPath, "utf8");
  for (const doc of catalogDocs) {
    const generatedPath = join(zhDocsRoot, `${doc.slug}.md`);
    if (!existsSync(generatedPath)) continue;
    const sourcePath = `docs/zh/${doc.slug}.md`;
    const block = `# ${doc.title}\n\nSource: ${sourceFileLink(sourcePath)}\n\n${readFileSync(generatedPath, "utf8").trim()}`;
    if (!zhLlmsFull.includes(block)) {
      failures.push(
        `${relative(repoRoot, zhLlmsFullPath)} is stale for ${sourcePath}; run pnpm docs:generate`,
      );
    }
  }
} else {
  failures.push(`${relative(repoRoot, zhLlmsFullPath)} is missing`);
}

for (const file of manualFiles) {
  const relativePath = relative(zhManualRoot, file);
  const generatedPath = join(zhDocsRoot, relativePath);
  if (!existsSync(generatedPath)) {
    failures.push(
      `${relative(repoRoot, file)} has no generated Chinese page at ${relative(repoRoot, generatedPath)}`,
    );
  }
}

for (const file of zhFiles) {
  const contents = readFileSync(file, "utf8");
  const relativePath = relative(zhDocsRoot, file);
  const isGeneratedReference =
    relativePath === "examples.md" ||
    relativePath === "llms.md" ||
    relativePath.startsWith("reference/");
  const isTopLevelPage = !relativePath.includes("/");
  if (contents.includes(stalePartialNotice)) {
    failures.push(`${relative(repoRoot, file)} still describes Chinese docs as partial summaries`);
  }
  if (isGeneratedReference && !contents.includes(generatedReferenceNotice)) {
    failures.push(`${relative(repoRoot, file)} is missing the generated-reference notice`);
  }
  if (
    isTopLevelPage &&
    !isGeneratedReference &&
    !generatedTopLevelPages.has(relativePath) &&
    !standaloneTopLevelPages.has(relativePath)
  ) {
    const manualPath = join(zhManualRoot, relativePath);
    if (!existsSync(manualPath)) {
      failures.push(
        `${relative(repoRoot, file)} is missing its manual source at ${relative(repoRoot, manualPath)}`,
      );
    }
  }
}

const themeIndex = readFileSync(themeIndexPath, "utf8");
if (themeIndex.includes("localeRedirect")) {
  failures.push("docs/.vitepress/theme/index.ts must not install automatic locale redirects");
}

if (existsSync(localeRedirectPath)) {
  failures.push("docs/.vitepress/theme/localeRedirect.ts should not exist");
}

if (failures.length > 0) {
  console.error("Chinese documentation verification failed:");
  for (const failure of failures) console.error(`- ${failure}`);
  process.exit(1);
}

console.log(
  "Verified Chinese docs are full-guide pages or marked generated references, with no auto-redirect active.",
);
